### ISSUE TITLE
SIP9 footprint names and adding SIP8 footprints

### ISSUE THREAD

**Issue by evanshultz** [KiCad/Housings_SIP.pretty#6]
I want to add the SIP8 footprint that is available for many ICS, for example [NJM4580](http://www.njr.com/semicon/PDF/NJM4580_E.pdf).

This is certainly the correct library, but I found two similar footprints named `SIP9_Housing.kicad_mod` and `SIP9_Housing_BigPads.kicad_mod`. Those names seem odd since `_Housing` isn't required to describe the package and `BigPads` is very nondescript (though https://github.com/KiCad/Housings_DIP.pretty uses `SmallPads` and `LongPads`.

I think just using `SIP8` and `SIP9` should be OK for the standard footprints. But for footprints with non-standard (big, small, long, oval, etc.) pads, is there an existing nomenclature? From what I see there isn't any guidelines or requirements for how to name those types of footprints.

**Comment by poeschlr** [comment]
I think this will be resolved with the new footprint naming convention: https://github.com/KiCad/kicad-library/issues/1447

**Comment by evanshultz** [comment]
Based off of the DIP section of your RFC, are you saying that `SIP-8` and `SIP-9` are good with you too?

**Comment by poeschlr** [comment]
Yes i would say SIP-8 is the correct beginning for the name of such a footprint.

As far as i can tell the footprints in this lib differ quite a bit. This is the reason why i do not yet have a naming convention for it.
I think it will be similar to the DIP naming convention.
